# This file is automatically generated by the build system.
# Do not edit this file directly.

from __future__ import annotations
from typing import TYPE_CHECKING

from multiconn_archicad.utilities.api import Utilities

from .official.addon import AddonCommands as OfficialAddonCommands
from .official.attribute import AttributeCommands as OfficialAttributeCommands
from .official.basic import BasicCommands as OfficialBasicCommands
from .official.classification import ClassificationCommands as OfficialClassificationCommands
from .official.component import ComponentCommands as OfficialComponentCommands
from .official.element_geometry import ElementGeometryCommands as OfficialElementGeometryCommands
from .official.element_listing import ElementListingCommands as OfficialElementListingCommands
from .official.element_relation import ElementRelationCommands as OfficialElementRelationCommands
from .official.layout_book import LayoutBookCommands as OfficialLayoutBookCommands
from .official.navigator_tree import NavigatorTreeCommands as OfficialNavigatorTreeCommands
from .official.property import PropertyCommands as OfficialPropertyCommands
from .official.view_map import ViewMapCommands as OfficialViewMapCommands
from .tapir.application import ApplicationCommands as TapirApplicationCommands
from .tapir.attribute import AttributeCommands as TapirAttributeCommands
from .tapir.classification import ClassificationCommands as TapirClassificationCommands
from .tapir.design_options import DesignOptionsCommands as TapirDesignOptionsCommands
from .tapir.element import ElementCommands as TapirElementCommands
from .tapir.element_creation import ElementCreationCommands as TapirElementCreationCommands
from .tapir.element_grouping import ElementGroupingCommands as TapirElementGroupingCommands
from .tapir.element_modification import ElementModificationCommands as TapirElementModificationCommands
from .tapir.favorites import FavoritesCommands as TapirFavoritesCommands
from .tapir.ifc import IfcCommands as TapirIfcCommands
from .tapir.issue_management import IssueManagementCommands as TapirIssueManagementCommands
from .tapir.keynote import KeynoteCommands as TapirKeynoteCommands
from .tapir.library import LibraryCommands as TapirLibraryCommands
from .tapir.mep import MepCommands as TapirMepCommands
from .tapir.navigator import NavigatorCommands as TapirNavigatorCommands
from .tapir.project import ProjectCommands as TapirProjectCommands
from .tapir.property import PropertyCommands as TapirPropertyCommands
from .tapir.revision_management import RevisionManagementCommands as TapirRevisionManagementCommands
from .tapir.script_ui import ScriptUiCommands as TapirScriptUiCommands
from .tapir.solid_element_operation import SolidElementOperationCommands as TapirSolidElementOperationCommands
from .tapir.teamwork import TeamworkCommands as TapirTeamworkCommands

if TYPE_CHECKING:
    from multiconn_archicad.clients.core.core_commands import CoreCommands


class TapirApi:
    """A container for all command groups of the Archicad Tapir API."""

    def __init__(self, core: CoreCommands):
        self.application = TapirApplicationCommands(core)
        self.attribute = TapirAttributeCommands(core)
        self.classification = TapirClassificationCommands(core)
        self.design_options = TapirDesignOptionsCommands(core)
        self.element = TapirElementCommands(core)
        self.element_creation = TapirElementCreationCommands(core)
        self.element_grouping = TapirElementGroupingCommands(core)
        self.element_modification = TapirElementModificationCommands(core)
        self.favorites = TapirFavoritesCommands(core)
        self.ifc = TapirIfcCommands(core)
        self.issue_management = TapirIssueManagementCommands(core)
        self.keynote = TapirKeynoteCommands(core)
        self.library = TapirLibraryCommands(core)
        self.mep = TapirMepCommands(core)
        self.navigator = TapirNavigatorCommands(core)
        self.project = TapirProjectCommands(core)
        self.property = TapirPropertyCommands(core)
        self.revision_management = TapirRevisionManagementCommands(core)
        self.script_ui = TapirScriptUiCommands(core)
        self.solid_element_operation = TapirSolidElementOperationCommands(core)
        self.teamwork = TapirTeamworkCommands(core)


class OfficialApi:
    """A container for all command groups of the Archicad Official API."""

    def __init__(self, core: CoreCommands):
        self.addon = OfficialAddonCommands(core)
        self.attribute = OfficialAttributeCommands(core)
        self.basic = OfficialBasicCommands(core)
        self.classification = OfficialClassificationCommands(core)
        self.component = OfficialComponentCommands(core)
        self.element_geometry = OfficialElementGeometryCommands(core)
        self.element_listing = OfficialElementListingCommands(core)
        self.element_relation = OfficialElementRelationCommands(core)
        self.layout_book = OfficialLayoutBookCommands(core)
        self.navigator_tree = OfficialNavigatorTreeCommands(core)
        self.property = OfficialPropertyCommands(core)
        self.view_map = OfficialViewMapCommands(core)


class UnifiedApi:
    """
    A unified, high-level, object-oriented interface for both the Tapir
    and Official Archicad JSON APIs, organized by command groups.
    """

    def __init__(self, core: CoreCommands):
        self.tapir = TapirApi(core)
        self.official = OfficialApi(core)
        self.utilities = Utilities(self)
