from typing import Any, Optional


def _get_target_from_path(defs: dict[str, Any], parent_name: str, path: list[str]) -> tuple[
    Optional[dict], Optional[dict], str]:
    """
    Navigates the schema dict. Returns (parent_of_target, target_schema, last_key_used).
    Automatically assumes segments are properties unless the segment is 'items'.
    """
    if parent_name not in defs:
        return None, None, ""

    current = defs[parent_name]

    # We need to keep track of the container to perform the $ref swap at the end
    parent_of_target = None
    last_key = ""

    for segment in path:
        parent_of_target = current
        last_key = segment

        if segment == "items":
            current = current.get("items")
        else:
            # Assume it is a property
            current = current.get("properties", {}).get(segment)

        if not isinstance(current, dict):
            return None, None, ""

    return parent_of_target, current, last_key


def _require_target(defs: dict[str, Any], parent_name: str, path: list[str]) -> tuple[Optional[dict], dict, str]:
    """
    Validates a patch target before patching. The patch calls are hand-maintained,
    so a missing parent or path means the upstream schema changed (e.g. a command
    was renamed) - fail loudly instead of silently skipping the patch and letting
    model names regress to autogenerated ones (LayoutsDatum instead of LayoutData).
    """
    if parent_name not in defs:
        raise KeyError(
            f"Schema patch target '{parent_name}' not found in the master schema. "
            f"The upstream command was probably renamed - update the patch in schema_patching.py."
        )

    container, target_schema, key = _get_target_from_path(defs, parent_name, path)
    if target_schema is None:
        raise KeyError(
            f"Schema patch path {path} does not resolve under '{parent_name}'. "
            f"The upstream schema probably changed - update the patch in schema_patching.py."
        )
    return container, target_schema, key


def extract_inline_schema(defs: dict[str, Any], parent_name: str, path: list[str], new_def_name: str):
    """
    Helper to extract an inline schema definition into a named $ref.
    Path is simplified: ['surveyPoint', 'position'] instead of ['properties', 'surveyPoint', 'properties', 'position']
    """
    container, target_schema, key = _require_target(defs, parent_name, path)

    if "$ref" in target_schema:
        return

    print(f"  -> Extracting Model {parent_name} / {path} to {new_def_name}")

    # 1. Store the target in top-level defs
    defs[new_def_name] = target_schema

    # 2. Replace the original location with a $ref
    if container:
        if key == "items":
            container["items"] = {"$ref": f"#/$defs/{new_def_name}"}
        else:
            container["properties"][key] = {"$ref": f"#/$defs/{new_def_name}"}


def extract_inline_enum(defs: dict[str, Any], parent_name: str, path: list[str], new_def_name: str):
    """
    Helper to extract an inline enum definition into a named $ref.
    """
    container, target_schema, key = _require_target(defs, parent_name, path)

    if "$ref" in target_schema:
        return

    if "enum" not in target_schema:
        print(f"  -> Warning: Expected enum at {parent_name} / {path}, but found none.")
        return

    print(f"  -> Extracting Enum {parent_name} / {path} to {new_def_name}")

    defs[new_def_name] = target_schema
    if container:
        if key == "items":
            container["items"] = {"$ref": f"#/$defs/{new_def_name}"}
        else:
            container["properties"][key] = {"$ref": f"#/$defs/{new_def_name}"}


def replace_inline_schema_with_ref(
    defs: dict[str, Any], parent_name: str, path: list[str], ref_name: str, preserve_description: bool = False
):
    """
    Replaces an inline schema at the given path with a $ref.
    Optionally preserves the original 'description' as a sibling keyword (valid in Draft 2019-09).
    """
    container, target_schema, key = _require_target(defs, parent_name, path)

    if "$ref" in target_schema:
        return

    print(f"  -> Replacing inline Model {parent_name} / {path} with {ref_name}")

    new_schema = {"$ref": f"#/$defs/{ref_name}"}

    if preserve_description and "description" in target_schema:
        new_schema["description"] = target_schema["description"]

    if container:
        if key == "items":
            container["items"] = new_schema
        else:
            container["properties"][key] = new_schema


def apply_permanent_patches(master_defs: dict[str, Any]):
    """
    Patches that are required permanently due to limitations in code generators
    or conscious design choices in our Python client (e.g., forcing better names).
    """
    print("Applying permanent schema patches...")

    # --- 1. Fix array element names (e.g., ZonesDatum -> ZoneData) ---
    creation_data_types = {
        "CreateColumnsParameters": ("columnsData", "ColumnData"),
        "CreateSlabsParameters": ("slabsData", "SlabData"),
        "CreatePolylinesParameters": ("polylinesData", "PolylineData"),
        "CreateObjectsParameters": ("objectsData", "ObjectData"),
        "CreateMeshesParameters": ("meshesData", "MeshData"),
        "CreateZonesParameters": ("zonesData", "ZoneData"),
        "CreateBeamsParameters": ("beamsData", "BeamData"),
        "CreateWallsParameters": ("wallsData", "WallData"),
        "CreateLabelsParameters": ("labelsData", "LabelData"),
        "CreateDetailsParameters": ("detailsData", "DetailData"),
        "CreateWorksheetsParameters": ("worksheetsData", "WorksheetData"),
        "CreateLayoutParameters": ("layoutsData", "LayoutData"),
        "CreateLayoutSubsetParameters": ("subsetsData", "SubsetData"),
        "CreateDrawingsParameters": ("drawingsData", "DrawingData"),
        "CreateWindowsParameters": ("windowsData", "WindowData"),
        "CreateDoorsParameters": ("doorsData", "DoorData"),
        "CreateMorphsParameters": ("morphsData", "MorphData"),
        "CreateRoofsParameters": ("roofsData", "RoofData"),
        "CreateOpeningsParameters": ("openingsData", "OpeningData"),
        "CreateAssociativeDimensionsParameters": ("dimensionsData", "AssociativeDimensionData"),
        "CreateAssociativeDimensionsOnSectionParameters": ("dimensionsData", "AssociativeDimensionOnSectionData"),
        "CreateWallThicknessDimensionsParameters": ("dimensionsData", "WallThicknessDimensionData"),
        "CreateSectionsParameters": ("sectionsData", "SectionData"),
        "CreateStairsParameters": ("stairsData", "StairData"),
        "CreateLampsParameters": ("lampsData", "LampData"),
        "CreateTextsParameters": ("textsData", "TextData"),
        "SetLayoutSettingsParameters": ("layoutsData", "LayoutSettingsData"),
        "CloneProjectMapItemToViewMapParameters": ("viewsData", "ViewCloneData"),
        "CreateViewsInViewMapParameters": ("viewsData", "ViewData"),
        "CreateMEPSystemsParameters": ("mepSystemDataArray", "MEPSystemData"),
        "CreateArcsParameters": ("arcsData", "ArcData"),
        "CreateCirclesParameters": ("circlesData", "CircleData"),
        "CreateHatchesParameters": ("hatchesData", "HatchData"),
        "CreateHotspotsParameters": ("hotspotsData", "HotspotData"),
        "CreateLineElementsParameters": ("linesData", "LineElementData"),
        "CreateSplinesParameters": ("splinesData", "SplineData"),
        "CreateKeynoteFoldersParameters": ("foldersData", "KeynoteFolderData"),
        "CreateKeynoteItemsParameters": ("itemsData", "KeynoteItemData"),
        "CreateKeynoteLabelsParameters": ("labelsData", "KeynoteLabelData"),
        "CreateMEPElementsParameters": ("elementsData", "MEPElementData"),
        "ConnectMEPElementsParameters": ("connectionsData", "MEPConnectionData"),
        "CreateMEPRoutingElementsParameters": ("routingElementsData", "MEPRoutingElementData"),
        "CreateLinesParameters": ("lineDataArray", "LineData"),
        "CreateFillsParameters": ("fillDataArray", "FillData"),
        "CreateZoneCategoriesParameters": ("zoneCategoryDataArray", "ZoneCategoryData"),
        "CreatePenTablesParameters": ("penTableDataArray", "PenTableData"),
        "CreateProfilesParameters": ("profileDataArray", "ProfileData"),
        "CreateCompositesParameters": ("compositeDataArray", "CompositeData"),
        "CreateSurfacesParameters": ("surfaceDataArray", "SurfaceData"),
        "CreateLayersParameters": ("layerDataArray", "LayerData"),
        "CreateBuildingMaterialsParameters": ("buildingMaterialDataArray", "BuildingMaterialData"),
    }

    for parent_model, (field_name, new_model_name) in creation_data_types.items():
        extract_inline_schema(master_defs, parent_model, [field_name, "items"], new_model_name)

    element_modification_datatypes = {
        "ModifyWallsParameters": ("wallsWithDetails", "WallWithDetails"),
        "ModifyBeamsParameters": ("beamsWithDetails", "BeamWithDetails"),
        "ModifySlabsParameters": ("slabsWithDetails", "SlabWithDetails"),
        "ModifyColumnsParameters": ("columnsWithDetails", "ColumnWithDetails"),
        "ModifyWindowsParameters": ("windowsWithDetails", "WindowWithDetails"),
        "ModifyDoorsParameters": ("doorsWithDetails", "DoorWithDetails"),
        "ModifyMorphsParameters": ("morphsWithDetails", "MorphWithDetails"),
        "ModifyRoofsParameters": ("roofsWithDetails", "RoofWithDetails"),
        "ModifyObjectsParameters": ("objectsWithDetails", "ObjectWithDetails"),
        "ModifyLampsParameters": ("lampsWithDetails", "LampWithDetails"),
        "ModifyMeshesParameters": ("meshesData", "MeshWithDetails"),
        "ModifyKeynoteFoldersParameters": ("foldersData", "KeynoteFolderModificationData"),
        "ModifyKeynoteItemsParameters": ("itemsData", "KeynoteItemModificationData"),
        "ModifyMEPRoutingElementsParameters": ("routingElementsData", "MEPRoutingElementModificationData"),
    }

    for parent_model, (field_name, new_model_name) in element_modification_datatypes.items():
        extract_inline_schema(master_defs, parent_model, [field_name, "items"], new_model_name)

    # ModifyMeshes wraps its payload one level deeper than the other Modify commands:
    # the MeshWithDetails wrapper (extracted above) carries the actual data in 'meshData'.
    extract_inline_schema(master_defs, "MeshWithDetails", ["meshData"], "MeshModificationData")

    extract_inline_schema(master_defs,"RevisionCustomSchemeData",["items"],"RevisionCustomSchemeEntry")

def apply_temporary_patches(master_defs: dict[str, Any]):
    """
    Patches that we expect to be fixed on the Tapir side eventually.
    Once the upstream schema is fixed, these can be deleted.
    """
    print("Applying temporary schema patches (pending upstream fixes)...")

    # --- Extract specific inline Enums ---
    extract_inline_enum(master_defs, "WallDetails", ["structureType"], "WallStructureType")
    extract_inline_enum(master_defs, "WallData", ["structureType"], "WallStructureType")
    extract_inline_enum(master_defs, "WallWithDetails", ["structureType"], "WallStructureType")
    extract_inline_enum(master_defs, "SlabDetails", ["structureType"], "SlabStructureType")
    extract_inline_enum(master_defs, "SlabWithDetails", ["structureType"], "SlabStructureType")
    extract_inline_enum(master_defs, "RoofData", ["structureType"], "RoofStructureType")
    extract_inline_enum(master_defs, "RoofWithDetails", ["structureType"], "RoofStructureType")

    # --- Name the per-attribute-type detail field enums (Tapir 1.5.4 attribute commands) ---
    extract_inline_enum(master_defs, "GetFillsParameters", ["fields", "items"], "FillAttributeField")
    extract_inline_enum(master_defs, "GetZoneCategoriesParameters", ["fields", "items"], "ZoneCategoryAttributeField")
    extract_inline_enum(master_defs, "GetMEPSystemsParameters", ["fields", "items"], "MEPSystemAttributeField")
    extract_inline_enum(master_defs, "GetPenTablesParameters", ["fields", "items"], "PenTableAttributeField")
    extract_inline_enum(master_defs, "GetProfilesParameters", ["fields", "items"], "ProfileAttributeField")
    extract_inline_enum(master_defs, "GetCompositesParameters", ["fields", "items"], "CompositeAttributeField")
    extract_inline_enum(master_defs, "CompositeSkin", ["type"], "CompositeSkinType")
    extract_inline_enum(master_defs, "GetSurfacesParameters", ["fields", "items"], "SurfaceAttributeField")
    extract_inline_enum(master_defs, "GetLayersParameters", ["fields", "items"], "LayerAttributeField")
    extract_inline_enum(master_defs, "GetBuildingMaterialsParameters", ["fields", "items"], "BuildingMaterialAttributeField")
    extract_inline_enum(master_defs, "GetLinesParameters", ["fields", "items"], "LineAttributeField")

    # --- Replace inline Coordinate2D properties in RotateElementsParameters ---
    replace_inline_schema_with_ref(master_defs, "RotateElementsParameters", ["elementsWithRotations", "items", "rotation", "beginPoint"], "Coordinate2D", preserve_description=True)
    replace_inline_schema_with_ref(master_defs, "RotateElementsParameters", ["elementsWithRotations", "items", "rotation", "endPoint"], "Coordinate2D", preserve_description=True)
    replace_inline_schema_with_ref(master_defs, "RotateElementsParameters", ["elementsWithRotations", "items", "rotation", "origin"], "Coordinate2D", preserve_description=True)

    # --- Extract conflicting inline Schemas ---
    extract_inline_schema(master_defs, "DimensionData", ["witnessPoints", "items"], "CoordinateWitnessPoint")
    extract_inline_schema(master_defs, "AssociativeDimensionData", ["witnessPoints", "items"], "AssociativeWitnessPoint")
    extract_inline_schema(master_defs, "RenameFavoritesParameters", ["renames", "items"], "FavoriteRename")
    extract_inline_schema(master_defs, "UpdatePropertyDefinitionsParameters", ["propertyDefinitions", "items"], "PropertyExpressionUpdate")
    extract_inline_schema(master_defs, "UpdateFavoritesFromElementsParameters", ["favoritesFromElements", "items"], "FavoritesFromElementUpdate")
    extract_inline_schema(master_defs, "RemoveSolidElementLinksParameters", ["solidLinks", "items"], "SolidLinkReference")
    extract_inline_schema(master_defs, "GetSolidElementLinksResult", ["solidLinks", "items"], "SolidLinksOfElement")
    extract_inline_schema(
        master_defs, "CreateProjectInfoFieldsParameters", ["projectInfoFields", "items"], "ProjectInfoFieldData"
    )
    extract_inline_schema(master_defs, "CreateDesignOptionsParameters", ["designOptions", "items"], "DesignOptionData")
    extract_inline_schema(
        master_defs,
        "GetDesignOptionCombinationsResult",
        ["designOptionCombinations", "items"],
        "DesignOptionCombinationDetails",
    )
    extract_inline_schema(
        master_defs,
        "CreateDesignOptionCombinationsParameters",
        ["designOptionCombinations", "items"],
        "DesignOptionCombinationData",
    )

    # --- Unify GeoLocation schemas ---
    extract_inline_schema(master_defs, "GetGeoLocationResult", ["projectLocation"], "ProjectLocation")
    extract_inline_schema(master_defs, "GetGeoLocationResult", ["surveyPoint", "position"], "SurveyPointPosition")
    extract_inline_schema(master_defs, "GetGeoLocationResult", ["surveyPoint", "geoReferencingParameters"],
                          "GeoReferencingParameters")
    extract_inline_schema(master_defs, "GetGeoLocationResult", ["surveyPoint"], "SurveyPoint")

    # Fix the bad inline schema by pointing it to the existing ArrayItem definition
    _, design_options, _ = _require_target(master_defs, "GetElementsOfDesignOptionsParameters", ["designOptions"])
    design_options["items"] = {"$ref": "#/$defs/DesignOptionIdArrayItem"}

    # Fix broken #ref in GetElementsOfDesignOptionsResult
    _, elements_of_design_options, _ = _require_target(
        master_defs, "GetElementsOfDesignOptionsResult", ["elementsOfDesignOptions"]
    )
    elements_of_design_options["items"] = {"$ref": "#/$defs/ElementsOfDesignOptionOrError"}

    replace_inline_schema_with_ref(master_defs, "SetGeoLocationParameters", ["projectLocation"], "ProjectLocation")
    replace_inline_schema_with_ref(master_defs, "SetGeoLocationParameters", ["surveyPoint"], "SurveyPoint")

    _, nav_window, _ = _require_target(master_defs, "NavigatorItemIdOrDatabaseIdAndWindowType", [])
    if "oneOf" in nav_window and len(nav_window["oneOf"]) > 1:
        # Extract the second union element (the inline object) to a new definition
        master_defs["DatabaseIdAndWindowType"] = nav_window["oneOf"][1]
        # Replace the inline object with a $ref
        nav_window["oneOf"][1] = {"$ref": "#/$defs/DatabaseIdAndWindowType"}

    # --- Unify Zoom schemas ---
    extract_inline_schema(master_defs, "ViewTransformations", ["zoom"], "Zoom")
    replace_inline_schema_with_ref(master_defs, "ViewSettings", ["zoom"], "Zoom")

    # --- Unify Morph Get/Create/Modify sub-schemas (Tapir 1.5.5 full morph parameter coverage) ---
    extract_inline_schema(master_defs, "MorphDetails", ["linkToSettings"], "LinkToSettings")
    replace_inline_schema_with_ref(master_defs, "MorphData", ["linkToSettings"], "LinkToSettings")
    replace_inline_schema_with_ref(master_defs, "MorphWithDetails", ["linkToSettings"], "LinkToSettings")
    extract_inline_enum(master_defs, "MorphDetails", ["displayOption"], "DisplayOption")
    replace_inline_schema_with_ref(master_defs, "MorphData", ["displayOption"], "DisplayOption")
    replace_inline_schema_with_ref(master_defs, "MorphWithDetails", ["displayOption"], "DisplayOption")
    extract_inline_enum(master_defs, "MorphDetails", ["viewDepthLimitation"], "ViewDepthLimitation")
    replace_inline_schema_with_ref(master_defs, "MorphData", ["viewDepthLimitation"], "ViewDepthLimitation")
    replace_inline_schema_with_ref(master_defs, "MorphWithDetails", ["viewDepthLimitation"], "ViewDepthLimitation")
    extract_inline_enum(master_defs, "MorphDetails", ["textureProjectionType"], "TextureProjectionType")
    replace_inline_schema_with_ref(master_defs, "MorphData", ["textureProjectionType"], "TextureProjectionType")
    replace_inline_schema_with_ref(master_defs, "MorphWithDetails", ["textureProjectionType"], "TextureProjectionType")
    extract_inline_schema(master_defs, "MorphDetails", ["coverFillOrientation"], "CoverFillOrientation")
    replace_inline_schema_with_ref(master_defs, "MorphData", ["coverFillOrientation"], "CoverFillOrientation")
    replace_inline_schema_with_ref(master_defs, "MorphWithDetails", ["coverFillOrientation"], "CoverFillOrientation")
    extract_inline_enum(master_defs, "CoverFillOrientation", ["type"], "CoverFillOrientationType")

    # --- Morph body geometry ---
    extract_inline_schema(master_defs, "MorphBody", ["polygons", "items"], "MorphPolygon")
    extract_inline_schema(master_defs, "MorphPolygon", ["holes", "items"], "MorphPolygonHole")

    # --- Design option link type ---
    extract_inline_enum(
        master_defs, "GetDesignOptionForElementsResult", ["designOptionForElements", "items", "type"], "DesignOptionLinkType"
    )

    # --- Unify Mesh Get/Create/Modify sub-schemas ---
    extract_inline_enum(master_defs, "MeshDetails", ["ridges"], "MeshRidges")
    replace_inline_schema_with_ref(master_defs, "MeshData", ["ridges"], "MeshRidges", preserve_description=True)
    replace_inline_schema_with_ref(master_defs, "MeshModificationData", ["ridges"], "MeshRidges", preserve_description=True)
    extract_inline_schema(master_defs, "MeshDetails", ["sublines", "items"], "MeshSubline")
    replace_inline_schema_with_ref(master_defs, "MeshData", ["sublines", "items"], "MeshSubline")
    replace_inline_schema_with_ref(master_defs, "MeshModificationData", ["sublines", "items"], "MeshSubline")

    # --- Line/Fill attribute creation sub-schemas (Tapir 1.5.4 attribute commands) ---
    # note - executes with already extracted objects lineDataArray -> LineData, fillDataArray -> FillData etc
    replace_inline_schema_with_ref(master_defs, "LineData", ["dashItems", "items"], "LineDashItem")
    extract_inline_schema(master_defs, "LineData", ["lineItems", "items"], "LineSymbolItemData")
    replace_inline_schema_with_ref(master_defs, "FillData", ["lineItems", "items"], "FillLineItem")
    replace_inline_schema_with_ref(master_defs, "FillData", ["symbolLines", "items"], "FillSymbolLine")
    replace_inline_schema_with_ref(master_defs, "FillData", ["symbolArcs", "items"], "FillSymbolArc")
    extract_inline_schema(master_defs, "PenTableData", ["pens", "items"], "PenData")
    extract_inline_schema(master_defs, "ProfileData", ["newSkins", "items"], "ProfileSkinData")
    extract_inline_schema(
        master_defs,
        "ProfileData",
        ["skinOverrides", "items", "edgeOverrides", "items"],
        "ProfileEdgeOverride",
    )

    # --- Attribute detail enums ---
    extract_inline_enum(master_defs, "FillAttribute", ["subType"], "FillSubType")
    extract_inline_enum(master_defs, "MEPSystemAttribute", ["domain", "items"], "MEPSystemDomain")
    extract_inline_enum(master_defs, "ProfileAttribute", ["useWith", "items"], "ProfileUseWith")

    # --- Drawing bounds ---
    extract_inline_schema(master_defs, "DrawingDetails", ["bounds"], "BoundingBox2D")

    extract_inline_schema(master_defs, "ProfileSkinData", ["contours", "items"], "ProfileSkinContour")
    replace_inline_schema_with_ref(master_defs, "ProfileSkinData", ["edgeOverrides", "items"], "ProfileEdgeOverride")

    # --- Solid element operation links (create side; Remove/Get variants are extracted above) ---
    extract_inline_schema(master_defs, "CreateSolidElementLinksParameters", ["solidLinks", "items"], "SolidLinkData")

    # --- Layout custom data (Get and Set sides have different required lists) ---
    extract_inline_schema(
        master_defs, "GetLayoutSettingsResult", ["layoutSettings", "items", "customData", "items"], "LayoutCustomData"
    )
    extract_inline_schema(master_defs, "LayoutSettingsData", ["customData", "items"], "LayoutCustomDataToSet")

    # --- Tapir 1.5.8: Data/Details/WithDetails now all carry the same enums inline ---
    extract_inline_enum(master_defs, "BeamDetails", ["anchorPoint"], "BeamAnchorPoint")
    for parent in ("BeamData", "BeamWithDetails"):
        replace_inline_schema_with_ref(master_defs, parent, ["anchorPoint"], "BeamAnchorPoint")
    extract_inline_enum(master_defs, "ColumnDetails", ["coreAnchor"], "ColumnCoreAnchor")
    for parent in ("ColumnData", "ColumnWithDetails"):
        replace_inline_schema_with_ref(master_defs, parent, ["coreAnchor"], "ColumnCoreAnchor")
    extract_inline_enum(master_defs, "SlabDetails", ["referencePlaneLocation"], "SlabReferencePlaneLocation")
    for parent in ("SlabData", "SlabWithDetails"):
        replace_inline_schema_with_ref(master_defs, parent, ["referencePlaneLocation"], "SlabReferencePlaneLocation")
    extract_inline_enum(master_defs, "WallDetails", ["referenceLineLocation"], "WallReferenceLineLocation")
    for parent in ("WallData", "WallWithDetails"):
        replace_inline_schema_with_ref(master_defs, parent, ["referenceLineLocation"], "WallReferenceLineLocation")
    extract_inline_enum(master_defs, "WallDetails", ["zoneRel"], "WallZoneRelation")
    replace_inline_schema_with_ref(master_defs, "WallWithDetails", ["zoneRel"], "WallZoneRelation")

    # Beam holes: same item shape and same discriminator in both models
    extract_inline_schema(master_defs, "BeamDetails", ["holes", "items"], "BeamHole")
    extract_inline_enum(master_defs, "BeamHole", ["type"], "BeamHoleType")
    replace_inline_schema_with_ref(master_defs, "BeamWithDetails", ["holes", "items"], "BeamHole")
    extract_inline_enum(master_defs, "HatchOrientation", ["type"], "HatchOrientationType")

    # geometryType and profileType are NOT shared: the modification models accept fewer
    # values than the read models (no Polygonal / no Poly), so they keep separate enums.
    extract_inline_enum(master_defs, "WallDetails", ["geometryType"], "WallGeometryType")
    extract_inline_enum(master_defs, "WallWithDetails", ["geometryType"], "WallModificationGeometryType")
    extract_inline_enum(master_defs, "WallDetails", ["profileType"], "WallProfileType")
    extract_inline_enum(master_defs, "WallWithDetails", ["profileType"], "WallModificationProfileType")

    # --- Tapir 1.5.8: CreateInteriorElevations payload ---
    extract_inline_schema(
        master_defs, "CreateInteriorElevationsParameters", ["interiorElevationsData", "items"], "InteriorElevationData"
    )

    # --- remove malformed Export Favorites result ---
    master_defs.pop("ExportFavoritesResult", None)

    # --- MEP enums/schemas (Tapir 1.5.6) ---
    extract_inline_enum(master_defs, "GetMEPElementsParameters", ["elementTypes", "items"], "MEPElementType")
    extract_inline_enum(master_defs, "GetMEPElementsParameters", ["domains", "items"], "MEPDomains")
    extract_inline_schema(master_defs, "GetMEPElementsResult", ["elements", "items"], "MEPElement")


    # --- DrawingSettings title name and numbering enums ---
    extract_inline_enum(master_defs, "DrawingSettings", ["nameType"], "DrawingNameType")
    extract_inline_enum(master_defs, "DrawingSettings", ["numberingType"], "DrawingNumberingType")

    # --- MEP Routing Cross Section Shape enum ---
    extract_inline_enum(
        master_defs, "MEPRoutingElementData", ["crossSectionShape"], "MEPCrossSectionShape"
    )
    replace_inline_schema_with_ref(
        master_defs,
        "MEPRoutingElementModificationData",
        ["crossSectionShape"],
        "MEPCrossSectionShape",
        preserve_description=True,
    )

    # --- Unify MEP Domain schemas to point to MEPSystemDomain ---
    replace_inline_schema_with_ref(
        master_defs, "MEPRoutingElementDetails", ["domain"], "MEPSystemDomain", preserve_description=True
    )
    replace_inline_schema_with_ref(
        master_defs, "MEPPortDetails", ["domain"], "MEPSystemDomain", preserve_description=True
    )
    replace_inline_schema_with_ref(
        master_defs, "GetMEPElementsParameters", ["domains", "items"], "MEPSystemDomain", preserve_description=True
    )
    replace_inline_schema_with_ref(
        master_defs,
        "GetMEPDistributionSystemsResult",
        ["distributionSystems", "items", "domain"],
        "MEPSystemDomain",
        preserve_description=True,
    )
    extract_inline_schema(
        master_defs, "GetMEPDistributionSystemsResult", ["distributionSystems", "items"], "MEPDistributionSystem"
    )
    replace_inline_schema_with_ref(
        master_defs, "MEPSystemData", ["domain"], "MEPSystemDomain", preserve_description=True
    )
    replace_inline_schema_with_ref(
        master_defs, "MEPElementData", ["domain"], "MEPSystemDomain", preserve_description=True
    )
    replace_inline_schema_with_ref(
        master_defs, "MEPRoutingElementData", ["domain"], "MEPSystemDomain", preserve_description=True
    )

    # GetMEPPreferenceTables accepts only two of the three domains, so it keeps its own enum
    extract_inline_enum(master_defs, "GetMEPPreferenceTablesParameters", ["domain"], "MEPPreferenceTableDomain")
    extract_inline_schema(master_defs, "GetMEPPreferenceTablesResult", ["tables", "items"], "MEPPreferenceTable")
    extract_inline_schema(master_defs, "MEPPreferenceTable", ["rows", "items"], "MEPPreferenceRow")

    # --- Extract 4-value discrete MEP element type enum ---
    extract_inline_enum(
        master_defs, "MEPElementData", ["type"], "MEPComponentType"
    )

    # --- Point MEPElement.type to the broad 11-value MEPElementType ---
    replace_inline_schema_with_ref(
        master_defs, "MEPElement", ["type"], "MEPElementType", preserve_description=True
    )

    # --- Tapir 1.5.7: Object/Lamp repeat the story visibility and home story link objects ---
    for parent in ("ObjectDetails", "ObjectData", "ObjectWithDetails", "LampData", "LampWithDetails"):
        replace_inline_schema_with_ref(master_defs, parent, ["visibility"], "StoryVisibility")
        replace_inline_schema_with_ref(master_defs, parent, ["linkToSettings"], "LinkToSettings")

    # --- GetRelationsOfElements returns a union of per-element-type relation objects ---
    _, element_relations, _ = _require_target(master_defs, "ElementRelationsOrError", [])
    relation_variants = [
        "WallRelations", "BeamRelations", "BeamSegmentRelations",
        "ZoneRelationsOfElement", "OpeningRelationsOfElement", "RoofOrShellRelationsOfElement",
    ]
    for index, variant_name in enumerate(relation_variants):
        branch = element_relations["oneOf"][index]
        if "$ref" in branch:
            continue
        master_defs[variant_name] = branch
        element_relations["oneOf"][index] = {"$ref": f"#/$defs/{variant_name}"}
