import argparse
import json
import pathlib
import sys
import textwrap

from code_generation.tapir.paths import tapir_paths


def clean_group_name(group: str) -> str:
    """
    Converts a group name like 'Attribute Commands' or '3D Commands (Visualization)'
    into a valid Python module name like 'attributes' or '3d_visualization'.
    """
    name = group.lower().replace(" commands", "").strip()
    name = "".join(c if c.isalnum() else "_" for c in name)
    name = "_".join(filter(None, name.split("_")))
    return name


class FileAssembler:
    """
    Takes a dictionary of commands with pre-generated method code and assembles
    the final Python package structure for the unified_api.
    """

    def __init__(self, commands_with_code: dict, output_dir: pathlib.Path):
        self._commands = commands_with_code
        self._output_dir = output_dir
        self._class_info = {"tapir": [], "official": []}

    def assemble(self):
        """Runs the entire assembly process."""
        print("--- Assembling Final API Files ---")
        self._create_directories()
        self._assemble_group_files()
        self._assemble_main_api_file()
        print(f"✅ Assembly complete. Final files are in: {self._output_dir}")

    def _create_directories(self):
        """Creates the output directory and the tapir/ and official/ subdirectories."""
        self._output_dir.mkdir(exist_ok=True)
        for source in ["tapir", "official"]:
            source_dir = self._output_dir / source
            source_dir.mkdir(exist_ok=True)
            (source_dir / "__init__.py").touch()
        (self._output_dir / "__init__.py").touch()
        print("  - Created base directory structure.")

    def _assemble_group_files(self):
        """Generates a .py file for each command group with dynamic imports."""
        print("  - Assembling command group files...")
        for source, groups in self._commands.items():
            for group_name, commands in groups.items():
                command_deps = set()
                type_deps = set()
                for cmd in commands:
                    command_deps.update(cmd.get("command_model_dependencies", []))
                    type_deps.update(cmd.get("type_model_dependencies", []))

                imports_block = self._create_imports_block(source, command_deps, type_deps)

                clean_name = clean_group_name(group_name)
                class_name = f"{clean_name.replace('_', ' ').title().replace(' ', '')}Commands"
                sorted_commands = sorted(commands, key=lambda c: c["name"])
                method_strings = [cmd["method_code"] for cmd in sorted_commands]

                file_content = self._create_group_class_content(class_name, imports_block, method_strings)

                output_path = self._output_dir / source / f"{clean_name}.py"
                output_path.write_text(file_content, encoding="utf-8")

                self._class_info[source].append({"module": clean_name, "class": class_name})

    def _create_imports_block(self, source: str, command_deps: set, type_deps: set) -> str:
        """Creates simple, single-line 'from ... import ...' statements."""
        lines = []
        if command_deps:
            sorted_deps = ", ".join(sorted(list(command_deps)))
            lines.append(f"from multiconn_archicad.models.{source}.commands import {sorted_deps}")
        if type_deps:
            sorted_deps = ", ".join(sorted(list(type_deps)))
            lines.append(f"from multiconn_archicad.models.{source}.types import {sorted_deps}")
        return "\n".join(lines)

    def _create_group_class_content(self, class_name: str, imports_block: str, methods: list[str]) -> str:
        """Creates the full Python code string for a single group class file."""
        header_lines = [
            "# This file is automatically generated by the build system.",
            "# Do not edit this file directly.",
            "",
            "from __future__ import annotations",
            "from typing import TYPE_CHECKING",
            "from pydantic import TypeAdapter",
            "",
            imports_block,
            "",
            "if TYPE_CHECKING:",
            "    from multiconn_archicad.clients.core.core_commands import CoreCommands",
        ]

        init_method = textwrap.dedent("""
            def __init__(self, core: CoreCommands):
                self._core = core
        """).strip()

        class_lines = [f"class {class_name}:"]
        class_lines.append(textwrap.indent(init_method, "    "))

        for method in methods:
            class_lines.append("\n")
            class_lines.append(textwrap.indent(method, "    "))

        return "\n".join(header_lines) + "\n\n\n" + "\n".join(class_lines) + "\n"

    def _assemble_main_api_file(self):
        """Generates the top-level api.py that ties everything together, aliasing imports."""
        print("  - Assembling main api.py file with aliased imports...")
        imports = []
        container_classes = []

        for source in ["tapir", "official"]:
            classes = sorted(self._class_info[source], key=lambda i: i["module"])
            container_name = f"{source.capitalize()}Api"

            class_body_lines = [
                f"class {container_name}:",
                f'    """A container for all command groups of the Archicad {source.capitalize()} API."""',
                "    def __init__(self, core: CoreCommands):",
            ]
            if not classes:
                class_body_lines.append("        pass")

            for info in classes:
                original_class_name = info["class"]
                aliased_class_name = f"{source.capitalize()}{original_class_name}"

                # Generate the aliased import statement
                imports.append(f"from .{source}.{info['module']} import {original_class_name} as {aliased_class_name}")

                # Use the aliased name in the __init__ method
                class_body_lines.append(f"        self.{info['module']} = {aliased_class_name}(core)")

            container_classes.append("\n".join(class_body_lines))

        unique_imports = sorted(list(set(imports)))

        content_lines = [
            "# This file is automatically generated by the build system.",
            "# Do not edit this file directly.",
            "",
            "from __future__ import annotations",
            "from typing import TYPE_CHECKING",
            "from multiconn_archicad.utilities.api import Utilities",
            "",
            "\n".join(unique_imports),
            "",
            "if TYPE_CHECKING:",
            "    from multiconn_archicad.clients.core.core_commands import CoreCommands",
            "",
            f'SUPPORTED_TAPIR_VERSION = "{tapir_paths.tapir_version}"',
            "",
            container_classes[0],
            "",
            "",
            container_classes[1],
            "",
            "",
            "class UnifiedApi:",
            '    """',
            "    A unified, high-level, object-oriented interface for both the Tapir",
            "    and Official Archicad JSON APIs, organized by command groups.",
            '    """',
            "    def __init__(self, core: CoreCommands):",
            "        self.tapir = TapirApi(core)",
            "        self.official = OfficialApi(core)",
            "        self.utilities = Utilities(self)",
        ]

        output_path = self._output_dir / "api.py"
        output_path.write_text("\n".join(content_lines) + "\n", encoding="utf-8")


def main():
    """Main script for Stage 3 of the pipeline."""
    parser = argparse.ArgumentParser(description="Stage 3: Assemble final API Python files from enriched JSON data.")
    parser.add_argument(
        "--input-file",
        required=True,
        type=pathlib.Path,
        help="Path to commands JSON with generated code (from Stage 2).",
    )
    parser.add_argument(
        "--output-dir", required=True, type=pathlib.Path, help="Final output directory for the generated API package."
    )
    args = parser.parse_args()

    if not args.input_file.is_file():
        print(f"❌ FATAL: Input file not found at: {args.input_file}", file=sys.stderr)
        sys.exit(1)

    with open(args.input_file, "r", encoding="utf-8") as f:
        commands_with_code = json.load(f)

    assembler = FileAssembler(commands_with_code, args.output_dir)
    assembler.assemble()


if __name__ == "__main__":
    main()
